#!/bin/sh
# Check if the session is DWM
if [ "$XDG_CURRENT_DESKTOP" = "dwm" ]; then
    # Autostart programs for DWM
    picom --config "$HOME/.config/picom/picom-ct.conf" &
    sh /home/marcus/.fehbg
    xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed" 0.3
    xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
    xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
fi

if [ "$XDG_CURRENT_DESKTOP" = "Qtile" ]; then
    picom --config "$HOME/.config/picom/picom.conf" &
    sh /home/marcus/.fehbg
    xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed" 0.3
    xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
    xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
fi
