# ChatGPT
windowrule=isnamedscratchpad:1,width:1900,height:1050,appid:brave-chatgpt.com__-Default
bind=ALT,c,toggle_named_scratchpad,brave-chatgpt.com__-Default,none,uwsm app -- brave --app=https://chatgpt.com

# Linear
windowrule=isnamedscratchpad:1,width:1900,height:1050,appid:brave-linear.app__dwellir-Default
bind=ALT,l,toggle_named_scratchpad,brave-linear.app__dwellir-Default,none,uwsm app -- brave --app=https://linear.app/dwellir

# Internal docs
windowrule=isnamedscratchpad:1,width:1900,height:1050,appid:brave-docs.internal.dwellir.com__docs-Default
bind=ALT,d,toggle_named_scratchpad,brave-docs.internal.dwellir.com__docs-Default,none,uwsm app -- brave --app=https://docs.internal.dwellir.com/docs

# Internal admin
windowrule=isnamedscratchpad:1,width:1900,height:1050,appid:brave-admin.internal.dwellir.com__-Default
bind=ALT,a,toggle_named_scratchpad,brave-admin.internal.dwellir.com__-Default,none,uwsm app -- brave --app=https://admin.internal.dwellir.com
