import = ["~/.config/alacritty/colors/draculasoothe.toml"]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 1

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[debug]
highlight_damage = false
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
WINIT_HIDPI_FACTOR = "1"
TERM = "xterm-256color"

[font]
size = 8.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[mouse]
hide_when_typing = false

#[[mouse.bindings]]
#action = "CopySelection"
#mouse = "Right"

[[mouse.bindings]]
action = "PasteSelection"
mods = "Control"
mouse = "Right"

[[mouse.bindings]]
action = "None"
mouse = "Middle"

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

#[shell]
#program = "/bin/bash"
#program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 6
y = 6
