[general]
import = ["colors/catppuccin-macchiato.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 1

[cursor]
unfocused_hollow = true
style = { blinking = "On", shape = "Block" }

[debug]
highlight_damage = false
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
WINIT_HIDPI_FACTOR = "1"
TERM = "xterm-256color"

[font]
normal = { family = "Inconsolata", style = "Regular" }
bold = { family = "Inconsolata", style = "Bold" }
bold_italic = { family = "Inconsolata", style = "Bold Italic" }
italic = { family = "Inconsolata", style = "Italic" }
glyph_offset = {x = 0, y = 0}
offset = { x = 0, y = 0 }
size = 11.0

[keyboard]
bindings = [
  { mods = "Control|Shift", key = "c", action = "Copy" },
  { mods = "Control|Shift", key = "v", action = "Paste" },
  { mods = "Control", key = "Equals", action = "IncreaseFontSize" },
  { mods = "Control", key = "Plus", action = "IncreaseFontSize" },
  { mods = "Control", key = "Minus", action = "DecreaseFontSize" },
  { mods = "Control", key = "Key0", action = "ResetFontSize" },
]

[mouse]
bindings = [
  { mods = "Control", mouse = "Right", action = "PasteSelection" },
  { mouse = "Middle", action = "None" }
]
hide_when_typing = false

[scrolling]
history = 100000
multiplier = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
blur = false
decorations = "full"
dimensions = {columns = 90, lines = 30}
dynamic_padding = false
dynamic_title = true
opacity = 1
padding = {x = 0, y = 0}
startup_mode = "Windowed"
