# System
alias apt="sudo apt"
alias sys="sudo systemctl"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias mkdir="mkdir -pv"
alias src="source ~/.bashrc"
alias ..="cd .."
alias w="watch -n 1 -c"
alias ip="ip -c"
# Configuration
alias alacrc="nvim ~/.config/alacritty/alacritty.yml"
alias brc="nvim ~/.bashrc"
# Applications
alias v="nvim"
alias sv="sudo nvim"
alias code="codium"
alias aplay="asciinema play -s 2.5"
alias arec="asciinema rec"
# Juju
alias wjs="watch -n 1 -c juju status --color"
alias wjsr="watch -n 1 -c juju status --color --relations"
alias js="juju status --color"
alias jsr="juju status --color --relations"
alias jm="juju models --all"
alias jc="juju controllers"
alias jcf="juju config"
alias ja="juju actions"
alias jra="juju run-action"
alias jaddssh="juju add-ssh-key '$(cat ~/.ssh/id_rsa.pub)'"
alias jsw="juju switch"
alias jswdl="juju switch dwellir-lagos"
alias jswdp="juju switch dwellir2-pionen"
alias jswds="juju switch dwellir-sodertalje"
alias jswdt="juju switch dwellir-tunis"
alias jswll="juju switch locallxd"
alias jswlk="juju switch localk8s"
# Microk8s
alias k="microk8s.kubectl"
# Tailscale
alias tailsdw="sudo tailscale switch marcus@dwellir.com"
alias tailsms="sudo tailscale switch marcussegerbjer@gmail.com"
